# Generated by Django 3.0.6 on 2020-05-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=20)),
                ('nazwisko', models.CharField(max_length=30)),
                ('stanowisko', models.CharField(max_length=20)),
                ('etat', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
